package credentialissuance

import kotlinx.serialization.Serializable

@Serializable
data class StartIssuanceResponse(
    /**
     * URL where wallet can view offer details
     */
    val credentialOfferUri: String,

    /**
     * One-time transaction code generated by CIS (optional)
     */
    val txCode: String? = null,

    /**
     * Website's internal identifier. If not provided, CIS will generate one.
     */
    val issuanceId: String,

    /**
     * Expire time in seconds
     */
    val expiresIn: Int
)
data class Message(val id: String?, val text: String)

data class UserDID(val userDID: String)


